on:
  push:
    branches:
      - "master"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master repo
        uses: actions/checkout@master
      - name: Build docker image
        run: docker build -t test:1.0.0 .
      - name: Save docker image to be used for production
        run: mkdir -p build && docker save -o build/output test:1.0.0
      - name: Push to master branch
        run: git add * && git commit --author="Satya Kripa Tirtha <satya.ktirtha@gmail.com>" -m "Created image" && git push
