on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out master repo
        uses: actions/checkout@master
      - name: Build docker image
        run: docker build -t test:1.0.0 
