on:
  push:
    branches:
      - "master"


permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master repo
        uses: actions/checkout@v4
        with:
          repository: 'satya-ktirtha/effective-meme'
          ref: 'master'
      - name: Build docker image
        run: docker build -t test:1.0.0 .
      - name: Save docker image to be used for production
        run: mkdir -p build && docker save -o build/output test:1.0.0
      - name: Push to master branch
        run: git config --global user.name "satya-ktirtha" && git config --global user.email "satya.ktirtha@gmail.com" && git add * && git commit --author="Satya Kripa Tirtha <satya.ktirtha@gmail.com>" -m "Created image" && git push
