on:
  push:
    branches:
      - "master"


permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master repo
        uses: actions/checkout@v4
        with:
          repository: 'satya-ktirtha/effective-meme'
          ref: 'master'
      - name: Login to GitHub Container Reg
        uses: docker/login-action@v1
          with: 
            registry: 'ghcr.io'
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t ghcr.io/satya-ktirtha/test:latest .
      - name: Pushing to docker registry
        run: docker push ghcr.io/satya-ktirtha/test:latest
